defaults:
  -
    scope:
      path: ''
    values:
      excerpt_separator: <!--more-->
  -
    scope:
      path: ""
      type: posts
    values:
      layout: 'post'
  -
    scope:
      path: ""
      type: pages
    values:
      layout: 'page'

name: 'Moshe Bergman'
description: 'Personal website'

paginate: 5
permalink: /:title

disqus-id: mbdev

markdown: 'kramdown'
kramdown:
  input: GFM
